// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class App
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Img { get; set; }

    public string Url { get; set; }

    public bool? Estado { get; set; }

    public DateTime? FechaCreado { get; set; }

    public string Detalle { get; set; }

    public string VersionCode { get; set; }

    public virtual ICollection<Modulo> Modulos { get; set; } = new List<Modulo>();

    public virtual ICollection<Rol> Rols { get; set; } = new List<Rol>();
}