// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class DispositivosConfiable
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public string TokenDispositivo { get; set; }

    public DateTime FechaRegistro { get; set; }

    public DateTime FechaExpiracion { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}