// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class ErrorLog
{
    public int ErrorId { get; set; }

    public DateTime ErrorDateTime { get; set; }

    public string ErrorMessage { get; set; }

    public int? ErrorSeverity { get; set; }

    public int? ErrorState { get; set; }

    public string ErrorProcedure { get; set; }

    public int? ErrorLine { get; set; }

    public string UserName { get; set; }

    public string HostName { get; set; }

    public string ApplicationName { get; set; }
}