// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiContabsv.Models.Seguridad;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiContabsv.Models.Seguridad
{
    public partial interface ISeguridadContextProcedures
    {
        Task<int> Cud_AppsAsync(string opt, int? id, string nombre, string img, string url, bool? estado, string detalle, string version_Code, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Cud_MenuResult>> Cud_MenuAsync(string opt, int? id, int? upper_id, int? app_id, string nombre, string icon, string url, bool? estado, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListaPermisosxUsuarioResult>> ListaPermisosxUsuarioAsync(int? idUduario, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListarAplicacionesResult>> ListarAplicacionesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListarModulosResult>> ListarModulosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListarModulosxAppsResult>> ListarModulosxAppsAsync(int? idApps, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListarUsuariosResult>> ListarUsuariosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> LogErrorAsync(string errorMessage, int? errorSeverity, int? errorState, string errorProcedure, int? errorLine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<LoginResult>> LoginAsync(string usuarioEmail, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ManageUsuarioResult>> ManageUsuarioAsync(string usuarioData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_GetPermisosUsuarioAsync(int? idUsuario, OutputParameter<string> json, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
