// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiContabsv.Models.Seguridad
{
    public partial class ListarAplicacionesResult
    {
        public int id { get; set; }
        [StringLength(100)]
        public string nombre { get; set; }
        [StringLength(2147483647)]
        public string img { get; set; }
        [StringLength(250)]
        public string url { get; set; }
        public bool? estado { get; set; }
        public DateTime? fecha_Creado { get; set; }
        [StringLength(255)]
        public string detalle { get; set; }
        [StringLength(100)]
        public string version_Code { get; set; }
    }
}
