// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiContabsv.Models.Seguridad
{
    public partial class ListarModulosxAppsResult
    {
        public int idModulo { get; set; }
        [StringLength(100)]
        public string descripcion { get; set; }
        public bool? activo { get; set; }
        public int? idApps { get; set; }
    }
}
