// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiContabsv.Models.Seguridad
{
    public partial class LoginResult
    {
        public int IdUsuario { get; set; }
        [StringLength(100)]
        public string Nombre { get; set; }
        [StringLength(100)]
        public string Apellido { get; set; }
        [StringLength(255)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Usuario { get; set; }
        public bool? Estado { get; set; }
        [StringLength(2)]
        public string Message { get; set; }
        public int? idCliente { get; set; }
        [StringLength(25)]
        public string nrcCliente { get; set; }
    }
}
