// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class Modulo
{
    public int IdModulo { get; set; }

    public string Descripcion { get; set; }

    public bool? Activo { get; set; }

    public int? IdApps { get; set; }

    public virtual App IdAppsNavigation { get; set; }

    public virtual ICollection<PermisosxRol> PermisosxRols { get; set; } = new List<PermisosxRol>();
}