// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class PermisosxRol
{
    public int IdPermiso { get; set; }

    public int? IdModulo { get; set; }

    public int? IdRol { get; set; }

    public bool? Estado { get; set; }

    public virtual Modulo IdModuloNavigation { get; set; }

    public virtual Rol IdRolNavigation { get; set; }
}