// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class Rol
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public bool? Estado { get; set; }

    public int? AppId { get; set; }

    public DateTime? FechaCreado { get; set; }

    public virtual App App { get; set; }

    public virtual ICollection<PermisosxRol> PermisosxRols { get; set; } = new List<PermisosxRol>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}