// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Seguridad;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Email { get; set; }

    public string Usuario1 { get; set; }

    public string Contraseña { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public bool? Estado { get; set; }

    public int? IdCliente { get; set; }

    public int? IdRol { get; set; }

    public int IntentosFallidos { get; set; }

    public DateTime? BloqueadoHasta { get; set; }

    public string CodigoVerificacion { get; set; }

    public DateTime? CodigoExpiracion { get; set; }

    public virtual ICollection<DispositivosConfiable> DispositivosConfiables { get; set; } = new List<DispositivosConfiable>();

    public virtual Rol IdRolNavigation { get; set; }
}