// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class ActividadesEconomica
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string Categoria { get; set; }

    public bool Activa { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }
}