// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class CatTipoItem
{
    public int IdTipoItem { get; set; }

    public string Descripcion { get; set; }
}