// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class ClientexClt
{
    public int IdClienteClt { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public bool? PersonaJuridica { get; set; }

    public string NombreRazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string DuiCliente { get; set; }

    public string RepresentanteLegal { get; set; }

    public string DuiRepresentanteLegal { get; set; }

    public string TelefonoCliente { get; set; }

    public string Celular { get; set; }

    public string Nrc { get; set; }

    public string TipoContribuyente { get; set; }

    public string NitCliente { get; set; }

    public int? IdCliente { get; set; }

    public virtual ICollection<VentaConsumidor> VentaConsumidors { get; set; } = new List<VentaConsumidor>();

    public virtual ICollection<VentaContribuyente> VentaContribuyentes { get; set; } = new List<VentaContribuyente>();
}