// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class Compra
{
    public int IdDocCompra { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateOnly? FechaEmision { get; set; }

    public DateOnly? FechaPresentacion { get; set; }

    public int? IdclaseDocumento { get; set; }

    public int? IdtipoDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public decimal? InternasExentas { get; set; }

    public decimal? InternacionalesExentasYONsujetas { get; set; }

    public decimal? ImportacionesYONsujetas { get; set; }

    public decimal? InternasGravadas { get; set; }

    public decimal? InternacionesGravadasBienes { get; set; }

    public decimal? ImportacionesGravadasBienes { get; set; }

    public decimal? ImportacionesGravadasServicios { get; set; }

    public decimal? CreditoFiscal { get; set; }

    public decimal? TotalCompras { get; set; }

    public int? IdTipoOperacion { get; set; }

    public int? IdClasificacion { get; set; }

    public int? IdTipoCostoGasto { get; set; }

    public int? IdSector { get; set; }

    public string NumeroAnexo { get; set; }

    public bool? Posteado { get; set; }

    public bool? Anulado { get; set; }

    public bool? Eliminado { get; set; }

    public int? IdCliente { get; set; }

    public bool? Combustible { get; set; }

    public string NumSerie { get; set; }

    public decimal? IvaRetenido { get; set; }

    public int? IdProveedor { get; set; }

    public virtual Clasificacion IdClasificacionNavigation { get; set; }

    public virtual Proveedore IdProveedorNavigation { get; set; }

    public virtual Sector IdSectorNavigation { get; set; }

    public virtual TipoOperacionCg IdTipoCostoGastoNavigation { get; set; }

    public virtual Operacione IdTipoOperacionNavigation { get; set; }

    public virtual ClaseDocumento IdclaseDocumentoNavigation { get; set; }

    public virtual TipoDocumento IdtipoDocumentoNavigation { get; set; }
}