// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiContabsv.Models.Contabilidad;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiContabsv.Models.Contabilidad
{
    public partial class ContabilidadContext
    {
        private IContabilidadContextProcedures _procedures;

        public virtual IContabilidadContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ContabilidadContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IContabilidadContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ContabilidadContextProcedures : IContabilidadContextProcedures
    {
        private readonly ContabilidadContext _context;

        public ContabilidadContextProcedures(ContabilidadContext context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_AnularVentaSimpleAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterjsonOutput = new SqlParameter
            {
                ParameterName = "jsonOutput",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = jsonOutput?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "jsonInput",
                    Size = -1,
                    Value = jsonInput ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterjsonOutput,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_AnularVentaSimple] @jsonInput = @jsonInput, @jsonOutput = @jsonOutput OUTPUT", sqlParameters, cancellationToken);

            jsonOutput?.SetValue(parameterjsonOutput.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_CalcularCostoFIFOAsync(int? idProducto, int? idCliente, decimal? cantidadVender, OutputParameter<decimal?> costoPromedio, OutputParameter<string> jsonDetalleCostos, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parametercostoPromedio = new SqlParameter
            {
                ParameterName = "costoPromedio",
                Precision = 18,
                Scale = 2,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = costoPromedio?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Decimal,
            };
            var parameterjsonDetalleCostos = new SqlParameter
            {
                ParameterName = "jsonDetalleCostos",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = jsonDetalleCostos?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idProducto",
                    Value = idProducto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "idCliente",
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "cantidadVender",
                    Precision = 10,
                    Scale = 2,
                    Value = cantidadVender ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                parametercostoPromedio,
                parameterjsonDetalleCostos,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_CalcularCostoFIFO] @idProducto = @idProducto, @idCliente = @idCliente, @cantidadVender = @cantidadVender, @costoPromedio = @costoPromedio OUTPUT, @jsonDetalleCostos = @jsonDetalleCostos OUTPUT", sqlParameters, cancellationToken);

            costoPromedio?.SetValue(parametercostoPromedio.Value);
            jsonDetalleCostos?.SetValue(parameterjsonDetalleCostos.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_ListarVentasAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterjsonOutput = new SqlParameter
            {
                ParameterName = "jsonOutput",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = jsonOutput?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "jsonInput",
                    Size = -1,
                    Value = jsonInput ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterjsonOutput,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_ListarVentas] @jsonInput = @jsonInput, @jsonOutput = @jsonOutput OUTPUT", sqlParameters, cancellationToken);

            jsonOutput?.SetValue(parameterjsonOutput.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_RegistrarVentaResult>> sp_RegistrarVentaAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterjsonOutput = new SqlParameter
            {
                ParameterName = "jsonOutput",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = jsonOutput?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "jsonInput",
                    Size = -1,
                    Value = jsonInput ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterjsonOutput,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_RegistrarVentaResult>("EXEC @returnValue = [dbo].[sp_RegistrarVenta] @jsonInput = @jsonInput, @jsonOutput = @jsonOutput OUTPUT", sqlParameters, cancellationToken);

            jsonOutput?.SetValue(parameterjsonOutput.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_RegistrarVentaSimpleAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterjsonOutput = new SqlParameter
            {
                ParameterName = "jsonOutput",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = jsonOutput?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "jsonInput",
                    Size = -1,
                    Value = jsonInput ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterjsonOutput,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_RegistrarVentaSimple] @jsonInput = @jsonInput, @jsonOutput = @jsonOutput OUTPUT", sqlParameters, cancellationToken);

            jsonOutput?.SetValue(parameterjsonOutput.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
