// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class Departamento
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Codigodep { get; set; }
}