// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiContabsv.Models.Contabilidad;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiContabsv.Models.Contabilidad
{
    public partial interface IContabilidadContextProcedures
    {
        Task<int> sp_AnularVentaSimpleAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_CalcularCostoFIFOAsync(int? idProducto, int? idCliente, decimal? cantidadVender, OutputParameter<decimal?> costoPromedio, OutputParameter<string> jsonDetalleCostos, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ListarVentasAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_RegistrarVentaResult>> sp_RegistrarVentaAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_RegistrarVentaSimpleAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
