// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class Proveedore
{
    public int IdProveedor { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public bool? PersonaJuridica { get; set; }

    public string NombreRazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string DuiCliente { get; set; }

    public string RepresentanteLegal { get; set; }

    public string DuiRepresentanteLegal { get; set; }

    public string TelefonoCliente { get; set; }

    public string Celular { get; set; }

    public string Nrc { get; set; }

    public string NitProveedor { get; set; }

    public int? IdCliente { get; set; }

    public string Email { get; set; }

    public string Direccion { get; set; }

    public int? IdSector { get; set; }

    public DateTime? Creado { get; set; }

    public string TipoContribuyente { get; set; }

    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

    public virtual Sector IdSectorNavigation { get; set; }
}