// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class Resolucion
{
    public int Id { get; set; }

    public int? IdTipoDocumento { get; set; }

    public string NumeroResolucion { get; set; }

    public string NumeroSerie { get; set; }

    public bool? Activo { get; set; }

    public int? IdCliente { get; set; }

    public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
}