// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class Sector
{
    public int IdSector { get; set; }

    public string CodigoSector { get; set; }

    public string Detalle { get; set; }

    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

    public virtual ICollection<Proveedore> Proveedores { get; set; } = new List<Proveedore>();
}