// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class TipoDocumento
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Codigo { get; set; }

    public string SectorP { get; set; }

    public string NombreCorto { get; set; }

    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

    public virtual ICollection<Resolucion> Resolucions { get; set; } = new List<Resolucion>();

    public virtual ICollection<VentaConsumidor> VentaConsumidors { get; set; } = new List<VentaConsumidor>();

    public virtual ICollection<VentaContribuyente> VentaContribuyentes { get; set; } = new List<VentaContribuyente>();
}