// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class VentasDetalle
{
    public int IdDetalle { get; set; }

    public int IdVenta { get; set; }

    public int NumeroLinea { get; set; }

    public int? IdProducto { get; set; }

    public string CodigoProducto { get; set; }

    public string Sku { get; set; }

    public string Descripcion { get; set; }

    public string UnidadMedida { get; set; }

    public decimal Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public decimal? Descuento { get; set; }

    public decimal? VentasExentas { get; set; }

    public decimal? VentasNoSujetas { get; set; }

    public decimal? VentasGravadas { get; set; }

    public decimal? IvaRetenido { get; set; }

    public decimal? MontoSujetoGrav { get; set; }

    public decimal Total { get; set; }

    public decimal? CostoUnitario { get; set; }

    public string Observaciones { get; set; }

    public decimal? Peso { get; set; }

    public decimal? Volumen { get; set; }

    public virtual Venta IdVentaNavigation { get; set; }
}