// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class Venta
{
    public int IdVenta { get; set; }

    public string TipoVenta { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public DateOnly? FechaPresentacion { get; set; }

    public DateOnly? FechaEmision { get; set; }

    public int? IdClaseDocumento { get; set; }

    public int? IdTipoDocumento { get; set; }

    public string NumeroResolucion { get; set; }

    public string SerieDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public string NumeroControlInterno { get; set; }

    public decimal? VentasExentas { get; set; }

    public decimal? VentasInternasExentasNoProporcionalidad { get; set; }

    public decimal? VentasNoSujetas { get; set; }

    public decimal? VentasGravadasLocales { get; set; }

    public decimal? ExportacionesCentroamerica { get; set; }

    public decimal? ExportacionesFueraCentroamerica { get; set; }

    public decimal? ExportacionesServicio { get; set; }

    public decimal? VentasZonasFrancasDpa { get; set; }

    public decimal? VentasTercerosNoDomiciliados { get; set; }

    public string NumeroMaquinaRegistradora { get; set; }

    public decimal? DebitoFiscal { get; set; }

    public decimal? DebitoFiscalVentasTerceros { get; set; }

    public decimal? TotalVentas { get; set; }

    public int? IdTipoOperacionCg { get; set; }

    public int? IdOperacion { get; set; }

    public int? NumeroAnexo { get; set; }

    public bool? Posteado { get; set; }

    public bool? Anulado { get; set; }

    public bool? Eliminado { get; set; }

    public int? IdCliente { get; set; }

    public int? IdClienteCit { get; set; }

    public string FormaPago { get; set; }

    public string CondicionPago { get; set; }

    public bool? EsDte { get; set; }

    public string CodigoGeneracion { get; set; }

    public string SelloRecepcion { get; set; }

    public string EstadoDte { get; set; }

    public DateTime? FechaEnvioMh { get; set; }

    public string JsonDte { get; set; }

    public string UsuarioRegistro { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string Observaciones { get; set; }

    public string TipoEnvio { get; set; }

    public decimal? CostoEnvio { get; set; }

    public decimal? PesoTotal { get; set; }

    public decimal? VolumenTotal { get; set; }

    public string DireccionEnvio { get; set; }

    public string ZonaEnvio { get; set; }

    public bool? ContraEntrega { get; set; }

    public string EstadoEnvio { get; set; }

    public virtual ClaseDocumento IdClaseDocumentoNavigation { get; set; }

    public virtual ClientexClt IdClienteCitNavigation { get; set; }

    public virtual Operacione IdOperacionNavigation { get; set; }

    public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }

    public virtual TipoOperacionCg IdTipoOperacionCgNavigation { get; set; }

    public virtual ICollection<VentasDetalle> VentasDetalles { get; set; } = new List<VentasDetalle>();
}