// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class VentaContribuyente
{
    public int IdVentaContribuyentes { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public DateOnly? FechaPresentacion { get; set; }

    public DateOnly? FechaEmisionDocumento { get; set; }

    public int? IdClaseDocumento { get; set; }

    public int? IdTipoDocumento { get; set; }

    public string NumeroResolucion { get; set; }

    public string SerieDocumento { get; set; }

    public string NumeroDocumento { get; set; }

    public string NumeroControlInterno { get; set; }

    public decimal? VentasExentas { get; set; }

    public decimal? VentasNoSujetas { get; set; }

    public decimal? VentasGravadasLocales { get; set; }

    public decimal? DebitoFiscal { get; set; }

    public decimal? VentasTercerosNoDomiciliados { get; set; }

    public decimal? DebitoFiscalVentasTerceros { get; set; }

    public decimal? TotalVentas { get; set; }

    public int? IdTipoOperacionCg { get; set; }

    public int? IdOperacion { get; set; }

    public int? NumeroAnexo { get; set; }

    public bool? Posteado { get; set; }

    public bool? Anulado { get; set; }

    public bool? Eliminado { get; set; }

    public int? IdCliente { get; set; }

    public int? IdClienteCit { get; set; }

    public virtual ClaseDocumento IdClaseDocumentoNavigation { get; set; }

    public virtual ClientexClt IdClienteCitNavigation { get; set; }

    public virtual Operacione IdOperacionNavigation { get; set; }

    public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }

    public virtual TipoOperacionCg IdTipoOperacionCgNavigation { get; set; }
}