// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabilidad;

public partial class VwReporteProfit
{
    public int? IdProducto { get; set; }

    public string Sku { get; set; }

    public string NombreProducto { get; set; }

    public string Descripcion { get; set; }

    public string Categoria { get; set; }

    public string Marca { get; set; }

    public string TipoProducto { get; set; }

    public string TipoItem { get; set; }

    public int IdVenta { get; set; }

    public string NumeroDocumento { get; set; }

    public DateOnly? FechaEmision { get; set; }

    public string FormaPago { get; set; }

    public int? IdCliente { get; set; }

    public string UsuarioRegistro { get; set; }

    public string NombreCliente { get; set; }

    public decimal Cantidad { get; set; }

    public decimal PrecioVenta { get; set; }

    public decimal? PrecioCompra { get; set; }

    public decimal? TotalVentas { get; set; }

    public decimal? TotalCostos { get; set; }

    public decimal? Profit { get; set; }

    public decimal? MargenPorcentaje { get; set; }

    public decimal Peso { get; set; }

    public decimal Volumen { get; set; }

    public decimal? DescuentoAplicado { get; set; }

    public string UnidadMedida { get; set; }

    public string ObservacionesVenta { get; set; }

    public int? Año { get; set; }

    public int? Mes { get; set; }

    public string NombreMes { get; set; }
}