// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApiContabsv.Models.Cultivo;

public partial class CultivoContext : DbContext
{
    public CultivoContext(DbContextOptions<CultivoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SensorDatum> SensorData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SensorDatum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__sensor_d__3213E83F00F8971F");

            entity.ToTable("sensor_data");

            entity.HasIndex(e => e.FechaHora, "IX_sensor_data_fecha");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EstadoWifi).HasColumnName("estado_wifi");
            entity.Property(e => e.FechaHora)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("fecha_hora");
            entity.Property(e => e.Humedad)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("humedad");
            entity.Property(e => e.Luz).HasColumnName("luz");
            entity.Property(e => e.MacAddress)
                .HasMaxLength(17)
                .IsUnicode(false)
                .HasColumnName("mac_address");
            entity.Property(e => e.NivelAgua)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("nivel_agua");
            entity.Property(e => e.Ph)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("ph");
            entity.Property(e => e.TempAgua)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("temp_agua");
            entity.Property(e => e.TempAire)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("temp_aire");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}