// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Cultivo;

public partial class SensorDatum
{
    public int Id { get; set; }

    public DateTime? FechaHora { get; set; }

    public decimal? TempAire { get; set; }

    public decimal? TempAgua { get; set; }

    public decimal? Humedad { get; set; }

    public decimal? NivelAgua { get; set; }

    public int? Luz { get; set; }

    public bool? EstadoWifi { get; set; }

    public string MacAddress { get; set; }

    public decimal? Ph { get; set; }
}