// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public bool? PersonaJuridica { get; set; }

    public string NombreRazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string DuiCliente { get; set; }

    public string RepresentanteLegal { get; set; }

    public string DuiRepresentanteLegal { get; set; }

    public string TelefonoCliente { get; set; }

    public string Celular { get; set; }

    public string Nrc { get; set; }

    public string NitCliente { get; set; }

    public string CodSector { get; set; }

    public string NomSector { get; set; }

    public string Direccion { get; set; }

    public string Correo { get; set; }

    public string Imagen { get; set; }

    public string TipoContribuyente { get; set; }

    public int? IdActividadEconomica { get; set; }

    public int? IdDepartamento { get; set; }

    public int? IdMunicipio { get; set; }

    public string ApiKey { get; set; }

    public string ApiSecret { get; set; }

    public string UserHacienda { get; set; }

    public string PassHacienda { get; set; }

    public string Token { get; set; }

    public bool? IsDeclarante { get; set; }

    public bool? IsDte { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public string EstadoCliente { get; set; }

    public int? UserDte { get; set; }

    public string Ambiente { get; set; }

    public string Facebook { get; set; }

    public string Instagram { get; set; }

    public string Whatsapp { get; set; }

    public virtual ICollection<HistorialPago> HistorialPagos { get; set; } = new List<HistorialPago>();

    public virtual ICollection<Suscripcione> Suscripciones { get; set; } = new List<Suscripcione>();
}