// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public bool? PersonaJuridica { get; set; }

    public string NombreRazonSocial { get; set; }

    public string NombreComercial { get; set; }

    public string DuiCliente { get; set; }

    public string RepresentanteLegal { get; set; }

    public string DuiRepresentanteLegal { get; set; }

    public string TelefonoCliente { get; set; }

    public string Celular { get; set; }

    public string Nrc { get; set; }

    public string NitCliente { get; set; }

    public string CodSector { get; set; }

    public string NomSector { get; set; }

    public string Direccion { get; set; }

    public string Correo { get; set; }
}