// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiContabsv.Models.Contabsv;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiContabsv.Models.Contabsv
{
    public partial class ContabsvContext
    {
        private IContabsvContextProcedures _procedures;

        public virtual IContabsvContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ContabsvContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IContabsvContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class ContabsvContextProcedures : IContabsvContextProcedures
    {
        private readonly ContabsvContext _context;

        public ContabsvContextProcedures(ContabsvContext context)
        {
            _context = context;
        }

        public virtual async Task<List<Crud_ClientexCltResult>> Crud_ClientexCltAsync(string clienteCltxData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClienteCltxData",
                    Size = -1,
                    Value = clienteCltxData ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Crud_ClientexCltResult>("EXEC @returnValue = [dbo].[Crud_ClientexClt] @ClienteCltxData = @ClienteCltxData", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Crud_DataClienteResult>> Crud_DataClienteAsync(string clienteData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClienteData",
                    Size = -1,
                    Value = clienteData ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Crud_DataClienteResult>("EXEC @returnValue = [dbo].[Crud_DataCliente] @ClienteData = @ClienteData", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Crud_ProveedoresResult>> Crud_ProveedoresAsync(string proveedoresData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProveedoresData",
                    Size = -1,
                    Value = proveedoresData ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Crud_ProveedoresResult>("EXEC @returnValue = [dbo].[Crud_Proveedores] @ProveedoresData = @ProveedoresData", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<DataClienteResult>> DataClienteAsync(int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idCliente",
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<DataClienteResult>("EXEC @returnValue = [dbo].[DataCliente] @idCliente = @idCliente", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<ListaClintesIntResult>> ListaClintesIntAsync(int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idCliente",
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<ListaClintesIntResult>("EXEC @returnValue = [dbo].[ListaClintesInt] @idCliente = @idCliente", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<ListaProveedoresResult>> ListaProveedoresAsync(int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idCliente",
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<ListaProveedoresResult>("EXEC @returnValue = [dbo].[ListaProveedores] @idCliente = @idCliente", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_ListarExistenciasAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterjsonOutput = new SqlParameter
            {
                ParameterName = "jsonOutput",
                Size = -1,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = jsonOutput?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "jsonInput",
                    Size = -1,
                    Value = jsonInput ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterjsonOutput,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_ListarExistencias] @jsonInput = @jsonInput, @jsonOutput = @jsonOutput OUTPUT", sqlParameters, cancellationToken);

            jsonOutput?.SetValue(parameterjsonOutput.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
