// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApiContabsv.Models.Contabsv;

public partial class ContabsvContext : DbContext
{
    public ContabsvContext(DbContextOptions<ContabsvContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__cliente__885457EE601E61BA");

            entity.ToTable("cliente");

            entity.Property(e => e.IdCliente).HasColumnName("idCliente");
            entity.Property(e => e.Apellidos)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("apellidos");
            entity.Property(e => e.Celular)
                .HasMaxLength(13)
                .HasColumnName("celular");
            entity.Property(e => e.CodSector)
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("codSector");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("correo");
            entity.Property(e => e.Direccion)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("direccion");
            entity.Property(e => e.DuiCliente)
                .HasMaxLength(10)
                .HasColumnName("duiCliente");
            entity.Property(e => e.DuiRepresentanteLegal)
                .HasMaxLength(10)
                .HasColumnName("duiRepresentanteLegal");
            entity.Property(e => e.NitCliente)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("nitCliente");
            entity.Property(e => e.NomSector)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nomSector");
            entity.Property(e => e.NombreComercial)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombreComercial");
            entity.Property(e => e.NombreRazonSocial)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("nombreRazonSocial");
            entity.Property(e => e.Nombres)
                .HasMaxLength(60)
                .IsUnicode(false)
                .HasColumnName("nombres");
            entity.Property(e => e.Nrc)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("nrc");
            entity.Property(e => e.PersonaJuridica).HasColumnName("personaJuridica");
            entity.Property(e => e.RepresentanteLegal)
                .HasMaxLength(120)
                .HasColumnName("representanteLegal");
            entity.Property(e => e.TelefonoCliente)
                .HasMaxLength(13)
                .HasColumnName("telefonoCliente");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}