// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiContabsv.Models.Contabsv
{
    public partial class DataClienteResult
    {
        public int idCliente { get; set; }
        [StringLength(60)]
        public string nombres { get; set; }
        [StringLength(60)]
        public string apellidos { get; set; }
        public bool? personaJuridica { get; set; }
        [StringLength(100)]
        public string nombreRazonSocial { get; set; }
        [StringLength(100)]
        public string nombreComercial { get; set; }
        [StringLength(10)]
        public string duiCliente { get; set; }
        [StringLength(120)]
        public string representanteLegal { get; set; }
        [StringLength(10)]
        public string duiRepresentanteLegal { get; set; }
        [StringLength(20)]
        public string telefonoCliente { get; set; }
        [StringLength(20)]
        public string celular { get; set; }
        [StringLength(25)]
        public string nrc { get; set; }
        [StringLength(20)]
        public string nitCliente { get; set; }
        [StringLength(2)]
        public string codSector { get; set; }
        [StringLength(100)]
        public string nomSector { get; set; }
        [StringLength(150)]
        public string direccion { get; set; }
        [StringLength(100)]
        public string correo { get; set; }
    }
}
