// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class HistorialPago
{
    public int IdPago { get; set; }

    public int IdSuscripcion { get; set; }

    public int IdCliente { get; set; }

    public DateTime FechaPago { get; set; }

    public decimal Monto { get; set; }

    public string MetodoPago { get; set; }

    public string EstadoPago { get; set; }

    public string NumeroFactura { get; set; }

    public DateTime FechaCreacion { get; set; }
}