// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiContabsv.Models.Contabsv;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ApiContabsv.Models.Contabsv
{
    public partial interface IContabsvContextProcedures
    {
        Task<List<Crud_ClientexCltResult>> Crud_ClientexCltAsync(string clienteCltxData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Crud_DataClienteResult>> Crud_DataClienteAsync(string clienteData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Crud_ProveedoresResult>> Crud_ProveedoresAsync(string proveedoresData, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<DataClienteResult>> DataClienteAsync(int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListaClintesIntResult>> ListaClintesIntAsync(int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListaProveedoresResult>> ListaProveedoresAsync(int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_ListarExistenciasAsync(string jsonInput, OutputParameter<string> jsonOutput, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
