// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class InvMovimiento
{
    public int IdMovimiento { get; set; }

    public int IdProducto { get; set; }

    public int IdCliente { get; set; }

    public string TipoMovimiento { get; set; }

    public int Cantidad { get; set; }

    public decimal? CostoUnitario { get; set; }

    public decimal? PrecioVentaUnitario { get; set; }

    public string Lote { get; set; }

    public string NumeroSerie { get; set; }

    public string Ubicacion { get; set; }

    public int? IdCompra { get; set; }

    public int? IdVenta { get; set; }

    public string NumeroDocumento { get; set; }

    public string MotivoMovimiento { get; set; }

    public string Responsable { get; set; }

    public DateTime FechaMovimiento { get; set; }

    public string Observaciones { get; set; }

    public Guid? LoteIngreso { get; set; }

    public decimal? CantidadDisponible { get; set; }

    public decimal? CostoReal { get; set; }

    public virtual InvProducto IdProductoNavigation { get; set; }
}