// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class InvOrdenesCompraDetalle
{
    public int IdDetalle { get; set; }

    public int IdCompra { get; set; }

    public int IdProducto { get; set; }

    public decimal CantidadOrdenada { get; set; }

    public decimal? CantidadRecibida { get; set; }

    public decimal CostoUnitario { get; set; }

    public decimal? PrecioVenta { get; set; }

    public string Lote { get; set; }

    public string Observaciones { get; set; }

    public virtual InvOrdenesCompra IdCompraNavigation { get; set; }
}