// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class InvOrdenesCompra
{
    public int IdCompra { get; set; }

    public int IdCliente { get; set; }

    public int IdProveedor { get; set; }

    public string NumeroOrden { get; set; }

    public DateTime? FechaOrden { get; set; }

    public DateTime? FechaCierre { get; set; }

    public string Estado { get; set; }

    public string Observaciones { get; set; }

    public string Responsable { get; set; }

    public virtual ICollection<InvOrdenesCompraDetalle> InvOrdenesCompraDetalles { get; set; } = new List<InvOrdenesCompraDetalle>();
}