// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class InvProducto
{
    public int IdProducto { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public int? IdMarca { get; set; }

    public int? IdCategoria { get; set; }

    public int? IdTipo { get; set; }

    public string CodigoBarra { get; set; }

    public decimal? PrecioCompra { get; set; }

    public decimal? PrecioVenta { get; set; }

    public bool? Estado { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public int? IdCliente { get; set; }

    public int? Stock { get; set; }

    public int? StockMinimo { get; set; }

    public int? StockMaximo { get; set; }

    public decimal? Peso { get; set; }

    public decimal? Volumen { get; set; }

    public string UnidadMedida { get; set; }

    public string Imagen { get; set; }

    public string Sku { get; set; }

    public int TipoItemId { get; set; }

    public virtual InvCategoria IdCategoriaNavigation { get; set; }

    public virtual InvMarca IdMarcaNavigation { get; set; }

    public virtual InvTiposProducto IdTipoNavigation { get; set; }

    public virtual ICollection<InvMovimiento> InvMovimientos { get; set; } = new List<InvMovimiento>();

    public virtual ICollection<InvStock> InvStocks { get; set; } = new List<InvStock>();
}