// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class InvStock
{
    public int IdStock { get; set; }

    public int? IdProducto { get; set; }

    public int Cantidad { get; set; }

    public string Ubicacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual InvProducto IdProductoNavigation { get; set; }
}