// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class InvTiposProducto
{
    public int IdTipo { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool? Estado { get; set; }

    public int? IdCliente { get; set; }

    public virtual ICollection<InvProducto> InvProductos { get; set; } = new List<InvProducto>();
}