// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class Plane
{
    public int IdPlan { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal PrecioMensual { get; set; }

    public decimal PrecioAnual { get; set; }

    public bool Activo { get; set; }

    public DateTime FechaCreacion { get; set; }
}