// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class Suscripcione
{
    public int IdSuscripcion { get; set; }

    public int IdCliente { get; set; }

    public int IdPlan { get; set; }

    public string TipoSuscripcion { get; set; }

    public string EstadoSuscripcion { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaVencimiento { get; set; }

    public decimal MontoSuscripcion { get; set; }

    public DateTime FechaCreacion { get; set; }
}