// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class SuscripcionDetalle
{
    public int IdDetalle { get; set; }

    public int IdSuscripcion { get; set; }

    public string Concepto { get; set; }

    public decimal PrecioUnitario { get; set; }

    public string TipoCobro { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime FechaVencimiento { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual Suscripcione IdSuscripcionNavigation { get; set; }
}