// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class Suscripcione
{
    public int IdSuscripcion { get; set; }

    public int IdCliente { get; set; }

    public string EstadoSuscripcion { get; set; }

    public DateTime FechaInicio { get; set; }

    public string PaypalSubscriptionId { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual ICollection<HistorialPago> HistorialPagos { get; set; } = new List<HistorialPago>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual ICollection<SuscripcionDetalle> SuscripcionDetalles { get; set; } = new List<SuscripcionDetalle>();
}