// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class UsuariosFirebase
{
    public int Id { get; set; }

    public string Uid { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public string FotoUrl { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public DateTime? UltimaSession { get; set; }
}