// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Contabsv;

public partial class VwSuscripcionesActiva
{
    public int IdSuscripcion { get; set; }

    public int IdCliente { get; set; }

    public string Nombres { get; set; }

    public string Correo { get; set; }

    public string NombrePlan { get; set; }

    public string TipoSuscripcion { get; set; }

    public string EstadoSuscripcion { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaVencimiento { get; set; }

    public decimal MontoSuscripcion { get; set; }

    public string EstadoVigencia { get; set; }

    public int? DiasParaVencer { get; set; }
}