// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class Address
{
    public int Id { get; set; }

    public int BranchId { get; set; }

    public string Department { get; set; }

    public string Municipality { get; set; }

    public string Address1 { get; set; }

    public string Complement { get; set; }

    public virtual BranchOffice Branch { get; set; }
}