// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class BranchOffice
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string EstablishmentCode { get; set; }

    public string EstablishmentCodeMh { get; set; }

    public string Email { get; set; }

    public string ApiKey { get; set; }

    public string ApiSecret { get; set; }

    public string Phone { get; set; }

    public string EstablishmentType { get; set; }

    public string PosCode { get; set; }

    public string PosCodeMh { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual User User { get; set; }
}