// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class ControlNumberSequence
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string DocumentType { get; set; }

    public string EstablishmentCode { get; set; }

    public string PosCode { get; set; }

    public long SequenceNumber { get; set; }

    public int Year { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Ambiente { get; set; }

    public virtual User User { get; set; }
}