// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class DomainEvent
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string EventType { get; set; }

    public string EventData { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool Processed { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<UserNotification> UserNotifications { get; set; } = new List<UserNotification>();
}