// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class DteBalanceTransaction
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string TransactionType { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}