// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ApiContabsv.Models.Dte;

public partial class dteContext : DbContext
{
    public dteContext(DbContextOptions<dteContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<BranchOffice> BranchOffices { get; set; }

    public virtual DbSet<ContingencyDocument> ContingencyDocuments { get; set; }

    public virtual DbSet<ControlNumberSequence> ControlNumberSequences { get; set; }

    public virtual DbSet<DomainEvent> DomainEvents { get; set; }

    public virtual DbSet<DteBalanceControl> DteBalanceControls { get; set; }

    public virtual DbSet<DteBalanceTransaction> DteBalanceTransactions { get; set; }

    public virtual DbSet<DteDetail> DteDetails { get; set; }

    public virtual DbSet<DteDocument> DteDocuments { get; set; }

    public virtual DbSet<FailedSequenceNumber> FailedSequenceNumbers { get; set; }

    public virtual DbSet<NotificationUser> NotificationUsers { get; set; }

    public virtual DbSet<Signer> Signers { get; set; }

    public virtual DbSet<SignerAssignment> SignerAssignments { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserNotification> UserNotifications { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Address>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__addresse__3213E83FB7ECC6BF");

            entity.ToTable("addresses");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address1)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.Complement)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("complement");
            entity.Property(e => e.Department)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("department");
            entity.Property(e => e.Municipality)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("municipality");

            entity.HasOne(d => d.Branch).WithMany(p => p.Addresses)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__addresses__branc__49C3F6B7");
        });

        modelBuilder.Entity<BranchOffice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__branch_o__3213E83FF055F229");

            entity.ToTable("branch_offices");

            entity.HasIndex(e => e.ApiKey, "UQ__branch_o__A2D78440681D3B33").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ApiKey)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("api_key");
            entity.Property(e => e.ApiSecret)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("api_secret");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.EstablishmentCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("establishment_code");
            entity.Property(e => e.EstablishmentCodeMh)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("establishment_code_mh");
            entity.Property(e => e.EstablishmentType)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .HasColumnName("establishment_type");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Phone)
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.PosCode)
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("pos_code");
            entity.Property(e => e.PosCodeMh)
                .HasMaxLength(4)
                .IsUnicode(false)
                .HasColumnName("pos_code_mh");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.BranchOffices)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__branch_of__user___46E78A0C");
        });

        modelBuilder.Entity<ContingencyDocument>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__continge__3213E83F2FBAC2F2");

            entity.ToTable("contingency_document");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ContingencyId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("contingency_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("document_type");
            entity.Property(e => e.JsonContent).HasColumnName("json_content");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.ContingencyDocuments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__contingen__user___5629CD9C");
        });

        modelBuilder.Entity<ControlNumberSequence>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__control___3213E83F4F2A18EF");

            entity.ToTable("control_number_sequence");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Ambiente)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("ambiente");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("document_type");
            entity.Property(e => e.EstablishmentCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("establishment_code");
            entity.Property(e => e.PosCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pos_code");
            entity.Property(e => e.SequenceNumber).HasColumnName("sequence_number");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.Year).HasColumnName("year");

            entity.HasOne(d => d.User).WithMany(p => p.ControlNumberSequences)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__control_n__user___5BE2A6F2");
        });

        modelBuilder.Entity<DomainEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__domain_e__3213E83F25661286");

            entity.ToTable("domain_event");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.EventData).HasColumnName("event_data");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("event_type");
            entity.Property(e => e.Processed).HasColumnName("processed");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.DomainEvents)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__domain_ev__user___6477ECF3");
        });

        modelBuilder.Entity<DteBalanceControl>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__dte_bala__3213E83F5644B206");

            entity.ToTable("dte_balance_control");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CurrentBalance)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("current_balance");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("last_updated");
            entity.Property(e => e.ReservedBalance)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("reserved_balance");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.DteBalanceControls)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__dte_balan__user___72C60C4A");
        });

        modelBuilder.Entity<DteBalanceTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__dte_bala__3213E83F7AA20ED9");

            entity.ToTable("dte_balance_transaction");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("transaction_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.DteBalanceTransactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__dte_balan__user___76969D2E");
        });

        modelBuilder.Entity<DteDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__dte_deta__3213E83FA259CDEF");

            entity.ToTable("dte_details");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ControlNumber)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("control_number");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("document_type");
            entity.Property(e => e.DteId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("dte_id");
            entity.Property(e => e.GenerationType).HasColumnName("generation_type");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("total_amount");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.DteDetails)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__dte_detai__user___4D94879B");
        });

        modelBuilder.Entity<DteDocument>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__dte_docu__3213E83FBF66E4CA");

            entity.ToTable("dte_document");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Ambiente)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("ambiente");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("document_type");
            entity.Property(e => e.DteId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("dte_id");
            entity.Property(e => e.ErrorDetails)
                .HasColumnType("text")
                .HasColumnName("error_details");
            entity.Property(e => e.ErrorMessage)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("error_message");
            entity.Property(e => e.HaciendaResponse)
                .HasColumnType("text")
                .HasColumnName("hacienda_response");
            entity.Property(e => e.JsonContent).HasColumnName("json_content");
            entity.Property(e => e.ReceptionStamp)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("reception_stamp");
            entity.Property(e => e.ResponseCode)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("response_code");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.DteDocuments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__dte_docum__user___52593CB8");
        });

        modelBuilder.Entity<FailedSequenceNumber>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__failed_s__3213E83FA48A8472");

            entity.ToTable("failed_sequence_number");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("document_type");
            entity.Property(e => e.ErrorMessage)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("error_message");
            entity.Property(e => e.SequenceNumber).HasColumnName("sequence_number");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.FailedSequenceNumbers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__failed_se__user___5FB337D6");
        });

        modelBuilder.Entity<NotificationUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__notifica__3213E83FAB8786C8");

            entity.ToTable("notification_users");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.EnabledPush)
                .HasDefaultValue(true)
                .HasColumnName("enabled_push");
            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("entity_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.NotificationUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__notificat__user___6D0D32F4");
        });

        modelBuilder.Entity<Signer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__signers__3213E83FED5A8BF6");

            entity.ToTable("signers");

            entity.HasIndex(e => e.SignerName, "UQ__signers__96295B92919FD64B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AvgResponseTimeMs)
                .HasDefaultValue(0)
                .HasColumnName("avg_response_time_ms");
            entity.Property(e => e.CertificatePassword)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("certificate_password");
            entity.Property(e => e.CertificatePath)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("certificate_path");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.CurrentLoad)
                .HasDefaultValue(0)
                .HasColumnName("current_load");
            entity.Property(e => e.EndpointUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasDefaultValue("http://localhost:8113/firmardocumento/")
                .HasColumnName("endpoint_url");
            entity.Property(e => e.HealthStatus)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("healthy")
                .HasColumnName("health_status");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.LastUsed).HasColumnName("last_used");
            entity.Property(e => e.MaxConcurrentSigns)
                .HasDefaultValue(5)
                .HasColumnName("max_concurrent_signs");
            entity.Property(e => e.Priority)
                .HasDefaultValue(1)
                .HasColumnName("priority");
            entity.Property(e => e.SignerName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("signer_name");
            entity.Property(e => e.TotalDocumentsSigned)
                .HasDefaultValue(0L)
                .HasColumnName("total_documents_signed");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<SignerAssignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__signer_a__3213E83F29A4F9EC");

            entity.ToTable("signer_assignments");

            entity.HasIndex(e => new { e.UserId, e.SignerId }, "UQ__signer_a__06321496C61948A3").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AssignedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("assigned_at");
            entity.Property(e => e.IsPrimary).HasColumnName("is_primary");
            entity.Property(e => e.LastUsed).HasColumnName("last_used");
            entity.Property(e => e.SignerId).HasColumnName("signer_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Signer).WithMany(p => p.SignerAssignments)
                .HasForeignKey(d => d.SignerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__signer_as__signe__123EB7A3");

            entity.HasOne(d => d.User).WithMany(p => p.SignerAssignments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__signer_as__user___114A936A");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83F9F1A10B4");

            entity.ToTable("users");

            entity.HasIndex(e => e.Email, "UQ__users__AB6E6164C8A5839B").IsUnique();

            entity.HasIndex(e => e.Phone, "UQ__users__B43B145F5AC17EF8").IsUnique();

            entity.HasIndex(e => e.Nrc, "UQ__users__DF90F580FCFD6C28").IsUnique();

            entity.HasIndex(e => e.Nit, "UQ__users__DF97D0E4382D3EB3").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Ambiente)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("ambiente");
            entity.Property(e => e.AuthType)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValue("standard")
                .HasColumnName("auth_type");
            entity.Property(e => e.BusinessName)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("business_name");
            entity.Property(e => e.ClienteId).HasColumnName("cliente_id");
            entity.Property(e => e.CommercialName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("commercial_name");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("created_at");
            entity.Property(e => e.EconomicActivity)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("economic_activity");
            entity.Property(e => e.EconomicActivityDesc)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("economic_activity_desc");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.HaciendaToken)
                .HasColumnType("text")
                .HasColumnName("hacienda_token");
            entity.Property(e => e.IsMaster).HasColumnName("is_master");
            entity.Property(e => e.JwtSecret)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("jwtSecret");
            entity.Property(e => e.Nit)
                .IsRequired()
                .HasMaxLength(17)
                .IsUnicode(false)
                .HasColumnName("nit");
            entity.Property(e => e.Nrc)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("nrc");
            entity.Property(e => e.ParentUserId).HasColumnName("parent_user_id");
            entity.Property(e => e.PasswordPri)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password_pri");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.TokenExpiresAt)
                .HasColumnType("datetime")
                .HasColumnName("token_expires_at");
            entity.Property(e => e.TokenLifetime)
                .HasDefaultValue(14)
                .HasColumnName("token_lifetime");
            entity.Property(e => e.TokenLifetimeDays)
                .HasDefaultValue(30)
                .HasColumnName("token_lifetime_days");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("updated_at");
            entity.Property(e => e.YearInDte).HasColumnName("year_in_dte");

            entity.HasOne(d => d.ParentUser).WithMany(p => p.InverseParentUser)
                .HasForeignKey(d => d.ParentUserId)
                .HasConstraintName("FK__users__parent_us__4222D4EF");
        });

        modelBuilder.Entity<UserNotification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_not__3213E83FC003F5AF");

            entity.ToTable("user_notifications");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DeliveryAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnName("delivery_at");
            entity.Property(e => e.DeliveryStatus)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("delivery_status");
            entity.Property(e => e.EventId).HasColumnName("event_id");
            entity.Property(e => e.Message)
                .IsRequired()
                .HasColumnName("message");
            entity.Property(e => e.NotificationType)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasColumnName("notification_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Event).WithMany(p => p.UserNotifications)
                .HasForeignKey(d => d.EventId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_noti__event__693CA210");

            entity.HasOne(d => d.User).WithMany(p => p.UserNotifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_noti__user___68487DD7");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}