// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class DteDocument
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string DteId { get; set; }

    public string DocumentType { get; set; }

    public string Status { get; set; }

    public string JsonContent { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}