// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class FailedSequenceNumber
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string DocumentType { get; set; }

    public long SequenceNumber { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}