// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class NotificationUser
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string EntityType { get; set; }

    public string Email { get; set; }

    public bool EnabledPush { get; set; }

    public virtual User User { get; set; }
}