// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class SignerAssignment
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int SignerId { get; set; }

    public bool IsPrimary { get; set; }

    public DateTime? AssignedAt { get; set; }

    public DateTime? LastUsed { get; set; }

    public virtual Signer Signer { get; set; }

    public virtual User User { get; set; }
}