// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class Signer
{
    public int Id { get; set; }

    public string SignerName { get; set; }

    public string CertificatePath { get; set; }

    public string CertificatePassword { get; set; }

    public string EndpointUrl { get; set; }

    public bool IsActive { get; set; }

    public int? MaxConcurrentSigns { get; set; }

    public int? CurrentLoad { get; set; }

    public int? Priority { get; set; }

    public string HealthStatus { get; set; }

    public long? TotalDocumentsSigned { get; set; }

    public int? AvgResponseTimeMs { get; set; }

    public DateTime? LastUsed { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<SignerAssignment> SignerAssignments { get; set; } = new List<SignerAssignment>();
}