// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class User
{
    public int Id { get; set; }

    public int? ClienteId { get; set; }

    public bool IsMaster { get; set; }

    public int? ParentUserId { get; set; }

    public string Nit { get; set; }

    public string Nrc { get; set; }

    public bool Status { get; set; }

    public string AuthType { get; set; }

    public string PasswordPri { get; set; }

    public string CommercialName { get; set; }

    public string EconomicActivity { get; set; }

    public string EconomicActivityDesc { get; set; }

    public string BusinessName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public bool YearInDte { get; set; }

    public int TokenLifetime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string JwtSecret { get; set; }

    public string HaciendaToken { get; set; }

    public DateTime? TokenExpiresAt { get; set; }

    public int? TokenLifetimeDays { get; set; }

    public virtual ICollection<BranchOffice> BranchOffices { get; set; } = new List<BranchOffice>();

    public virtual ICollection<ContingencyDocument> ContingencyDocuments { get; set; } = new List<ContingencyDocument>();

    public virtual ICollection<ControlNumberSequence> ControlNumberSequences { get; set; } = new List<ControlNumberSequence>();

    public virtual ICollection<DomainEvent> DomainEvents { get; set; } = new List<DomainEvent>();

    public virtual ICollection<DteBalanceControl> DteBalanceControls { get; set; } = new List<DteBalanceControl>();

    public virtual ICollection<DteBalanceTransaction> DteBalanceTransactions { get; set; } = new List<DteBalanceTransaction>();

    public virtual ICollection<DteDetail> DteDetails { get; set; } = new List<DteDetail>();

    public virtual ICollection<DteDocument> DteDocuments { get; set; } = new List<DteDocument>();

    public virtual ICollection<FailedSequenceNumber> FailedSequenceNumbers { get; set; } = new List<FailedSequenceNumber>();

    public virtual ICollection<User> InverseParentUser { get; set; } = new List<User>();

    public virtual ICollection<NotificationUser> NotificationUsers { get; set; } = new List<NotificationUser>();

    public virtual User ParentUser { get; set; }

    public virtual ICollection<SignerAssignment> SignerAssignments { get; set; } = new List<SignerAssignment>();

    public virtual ICollection<UserNotification> UserNotifications { get; set; } = new List<UserNotification>();
}