// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiContabsv.Models.Dte;

public partial class UserNotification
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int EventId { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public string DeliveryStatus { get; set; }

    public DateTime? DeliveryAt { get; set; }

    public virtual DomainEvent Event { get; set; }

    public virtual User User { get; set; }
}